---
# tasks file for gitlab_runner_setup
- include_role:
    name: jamesjonesconsulting.podman_socket_group_permissions.permissions_setup
  vars:
    podman_user_group: "{{ gitlab_runner_podman_group }}"
    podman_users:
      - "{{ gitlab_runner_username }}"
# - name: Setup the GitLab Runner Repository 
#   shell: |
#     curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
# - name: Adjust version if not supported 
#   block:
#     - name: Set best compatible version 
#       set_fact:
#         releasever: "{{ (supported_gitab_runners[ansible_facts['distribution']] | max) if ((ansible_facts['distribution_major_version'] | int) > (supported_gitab_runners[ansible_facts['distribution']] | max)) else (supported_gitab_runners[ansible_facts['distribution']] | min) }}"
#     - debug:
#         msg: "{{ releasever }} selected"


#   when: 
#     - "(ansible_facts['distribution_major_version'] | int) not in supported_gitab_runners[ansible_facts['distribution']]"
  
  
- name: Setup the GitLab repo
- block:
    - name: Setup the GitLab Runner Repository 
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
  rescue:
    - debug:
        msg: "Something with your os and distribution version wasn't supported, attempting to pass those based on known compatibility."
    - name: Setup the GitLab Runner Repository 
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
      environment: 
        dist: "{{ (supported_gitab_runners[ansible_facts['distribution']]['dist'] | max) if ((ansible_facts['distribution_major_version'] | int) > (supported_gitab_runners[ansible_facts['distribution']]['dist'] | max)) else (supported_gitab_runners[ansible_facts['distribution']]['dist'] | min) }}"
        os: "{{ supported_gitab_runners[ansible_facts['distribution']]['os'] }}"
        

    # - name: Download GitLab Runner yum repo file
    #   ansible.builtin.get_url:
    #     url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/config_file.repo?os={{ os }}&dist={{ dist }}&source=script"
    #     dest: /etc/yum.repos.d/runner_gitlab-runner.repo
    #   vars:
    #     dist: "{{ (supported_gitab_runners[ansible_facts['distribution']] | max) if ((ansible_facts['distribution_major_version'] | int) > (supported_gitab_runners[ansible_facts['distribution']] | max)) else (supported_gitab_runners[ansible_facts['distribution']] | min) }}"
    #     os: "{{ supported_gitab_runner_dists[ansible_facts['distribution']].os_name }}"
#   when:
#     - "ansible_facts['distribution'] in supported_gitab_runner_dists"
# - block:
#     - debug:
#         msg: "Your distribution {{ ansible_facts['distribution'] }} is either not supported by GitLab or by this collection"
#   when:
#     - "ansible_facts['distribution'] not in supported_gitab_runner_dists"
