---
- name: Setup the GitLab repo
  block:
    - name: Setup the GitLab Runner Repository 
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
  rescue:
    - debug:
        msg: "Something with your os and distribution version wasn't supported, attempting to pass those based on known compatibility."
    - name: Setup the GitLab Runner Repository 
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
      environment: 
        dist: "{{ (supported_gitab_runners[ansible_facts['distribution']]['dist'] | max) if ((ansible_facts['distribution_major_version'] | int) > (supported_gitab_runners[ansible_facts['distribution']]['dist'] | max)) else (supported_gitab_runners[ansible_facts['distribution']]['dist'] | min) }}"
        os: "{{ supported_gitab_runners[ansible_facts['distribution']]['os'] }}"
- name: Ensure the latest version of the gitlab-runner is installed
  yum:
    name: gitlab-runner
    state: latest
- name: Now that the gitlab-runner and it's user exists, setup Podman socket permissions
  include_role:
    name: jamesjonesconsulting.podman_socket_group_permissions.permissions_setup
  vars:
    podman_user_group: "{{ gitlab_runner_podman_group }}"
    podman_users:
      - "{{ gitlab_runner_username }}"
- name: Get list of configured runners for this hostname 
  shell: |
    gitlab-runner list 2>&1 | grep {{ inventory_hostname }} | tr -s ' ' | cut -d' ' -f4,5
  register: configured_runners
- name: Remove existing runner 
  shell: |
    gitlab-runner unregister --url {{ url }} --token {{ token }}
  vars:
    token: "{{ runner_conf.split()[0].split('=')[1] }}"
    url: "{{ runner_conf.split()[1].split('=')[1] | trim }}"
  loop: "{{ configured_runners.stdout_lines }}"
  loop_control:
    loop_var: runner_conf
- name: Cleanup unregistered config entries
  shell: |
    gitlab-runner verify --delete
- name: Register one or more runners
  include_tasks: multi-runner.yml
  loop: "{{ range(1, ((gitlab_runner_count | default(1)) | int) + 1,1) | list }}"
  loop_control:
    loop_var: runner_suffix
- name: Ensure the right setting persist after registering
  command: |
    sed -i 's/privileged = false/privileged = true/g' /etc/gitlab-runner/config.toml
    sed -i 's/tls_verify = true/tls_verify = false/g' /etc/gitlab-runner/config.toml
    sed -i 's/disable_cache = false/network = host/g' /etc/gitlab-runner/config.toml
    sed -i '/disable_entrypoint_overwrite/d' /etc/gitlab-runner/config.toml
    sed -i '/oom_kill_disable/d' /etc/gitlab-runner/config.toml
    sed -i '/volumes/d' /etc/gitlab-runner/config.toml
    sed -i '/shm_size/d' /etc/gitlab-runner/config.toml
- name: Restart gitlab-runner
  ansible.builtin.systemd:
    name: gitlab-runner
    state: restarted