---
# tasks file for gitlab_runner_setup
- name: Setup the GitLab repo
  block:
    - name: Setup the GitLab Runner Repository 
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
  rescue:
    - debug:
        msg: "Something with your os and distribution version wasn't supported, attempting to pass those based on known compatibility."
    - name: Setup the GitLab Runner Repository 
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
      environment: 
        dist: "{{ (supported_gitab_runners[ansible_facts['distribution']]['dist'] | max) if ((ansible_facts['distribution_major_version'] | int) > (supported_gitab_runners[ansible_facts['distribution']]['dist'] | max)) else (supported_gitab_runners[ansible_facts['distribution']]['dist'] | min) }}"
        os: "{{ supported_gitab_runners[ansible_facts['distribution']]['os'] }}"
- name: Ensure the latest version of the gitlab-runner is installed
  yum:
    name: gitlab-runner
    state: latest
- name: Now that the gitlab-runner and it's user exists, setup Podman socket permissions
  include_role:
    name: jamesjonesconsulting.podman_socket_group_permissions.permissions_setup
  vars:
    podman_user_group: "{{ gitlab_runner_podman_group }}"
    podman_users:
      - "{{ gitlab_runner_username }}"
- debug:
    msg: "{{ gitlab_runner_tags }}"
- name: Get list of configured runners for this hostname 
  shell: |
    gitlab-runner list 2>&1 | grep {{ inventory_hostname }} | tr -s ' ' | cut -d' ' -f4,5
  register: configured_runners
- debug:
    msg: |
      {{ token }} and {{ url }}
  vars:
    token: "{{ runner_conf.split()[0].split('=')[1] }}"
    url: "{{ runner_conf.split()[1].split('=')[1] }}"
  loop: "{{ configured_runners.split('\n') }}"
  loop_control:
    loop_var: runner_conf
# - block:
#   - name: Verify if the gitlab-runner is already setup 
#     shell: |
#       gitlab-runner verify --name {{ inventory_hostname }} --delete
#     register: gitlab_runner_exists
#     failed_when: "gitlab_runner_exists.rc == 0"
#   rescue:
#     - name: Remove existing runner 
#       shell: |
#         gitlab-runner unregister --name {{ inventory_hostname }}
# - name: Register the gitlab-runner non-interactively
#   shell: |
#     gitlab-runner register --non-interactive --url {{ gitlab_runner_url }} \
#       --registration-token {{ gitlab_runner_registration_token }} \
#       --executor "docker" \
#       --docker-image "quay.io/podman/stable" \
#       --docker-host "unix:///run/podman/podman.sock" \
#       --docker-tlsverify "false" \
#       --docker-privileged "true" \
#       --docker-network-mode "host" \
#       --description {{ inventory_hostname }} \
#       {{ ('--tag-list ' + (gitlab_runner_tags | join(',') | quote)) if (gitlab_runner_tags | default([]) | length) > 0 else '--run-untagged' }} \
#       --locked="false"
#   no_log: true
