---
# tasks file for gitlab_runner_setup
- include_role:
    name: jamesjonesconsulting.podman_socket_group_permissions.permissions_setup
  vars:
    podman_user_group: "{{ gitlab_runner_podman_group }}"
    podman_users:
      - "{{ gitlab_runner_username }}"
- name: Setup the GitLab repo
  block:
    - name: Setup the GitLab Runner Repository 
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
  rescue:
    - debug:
        msg: "Something with your os and distribution version wasn't supported, attempting to pass those based on known compatibility."
    - name: Setup the GitLab Runner Repository 
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
      environment: 
        dist: "{{ (supported_gitab_runners[ansible_facts['distribution']]['dist'] | max) if ((ansible_facts['distribution_major_version'] | int) > (supported_gitab_runners[ansible_facts['distribution']]['dist'] | max)) else (supported_gitab_runners[ansible_facts['distribution']]['dist'] | min) }}"
        os: "{{ supported_gitab_runners[ansible_facts['distribution']]['os'] }}"
