---
- debug:
    msg: "{{ runner_suffix }}"
- set_fact:
    register_options: []
- set_fact:
    register_options: "{{ (register_options | default([])) + [opt.option] }}"
  when:
    - "opt.valid"
  loop:
    - option: "--tag-list {{ tag_list }}"
      valid: "{{ (gitlab_runner_tags | default([])) | length | bool }}"
    - option: "--run-untagged"
      valid: "{{ gitlab_runner_run_untagged | default(true) }}"
  loop_control:
    loop_var: opt
  vars:
    tag_list: "{{ gitlab_runner_tags | join(',') }}"
- debug:
    msg: "{{ register_options | join(' ') }}"
- name: Register the gitlab-runner non-interactively
  shell: |
    gitlab-runner register --non-interactive --url {{ gitlab_runner_url }} \
      --registration-token {{ gitlab_runner_registration_token }} \
      --executor "docker" \
      --docker-image "quay.io/podman/stable" \
      --docker-host "unix:///run/podman/podman.sock" \
      --docker-tlsverify "false" \
      --docker-privileged "true" \
      --docker-network-mode "host" \
      --description "{{ inventory_hostname }}" \
      {{ register_options | join(' ') }} \
      --locked="false"
  no_log: true
#       {{ ('--tag-list ' + (gitlab_runner_tags | join(',') | quote)) if (gitlab_runner_tags | default([]) | length) > 0 else '--run-untagged' }} \
